### ISSUE TITLE
Current line highlight don't contain whole line if it's longer then the width of editor

### ISSUE THREAD

**Issue by jcubic** [mishoo/ymacs#17]
if you have very long line that and it's not fiting into editor width when you move cursor to the right only part of the line is higlighted as current line.

This fixed the issue:
```css
.Ymacs-frame-content {
    float: left;
}
```

**Comment by jcubic** [comment]
This will not fix the issue when line is shorter.

**Comment by jcubic** [comment]
This fixed the issue:
```css
.Ymacs-frame-content {
    display: inline-block;
    min-width: 100%;
}
```
